# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_delete_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
