# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.CharField(max_length=60),
        ),
    ]
